# Generated by Django 3.2.7 on 2021-11-23 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecnac',
            field=models.DateField(default=datetime.date.today, verbose_name='fecnac'),
        ),
    ]
